apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-dev-mpio/appstudio/dc-metro-map@sha256:a0d9da2b83aaf6e5ba175efcad0820956a51eaaf2eda9151d59ff57752227d8c
        name: my-nodejs
        resources: {}
status: {}
